### ISSUE TITLE
Node 16 (LTS) support

### ISSUE THREAD

**Issue by loan-laux** [bigcommerce/checkout-js#1078]
Node 14 is headed towards EOL and [will stop receiving security updates in 6 months](https://endoflife.date/nodejs).

This project should support and enforce with the `engines` property in `package.json` the current LTS version of Node which is 16.18.

I've tried swapping out Node 14 for 16 but am getting a `node-gyp` compilation error about `node-sass` when `npm install`ing:

```
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/loanlaux/Development/bigcommerce-checkout/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.5.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/loanlaux/Development/bigcommerce-checkout/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/loanlaux/Development/bigcommerce-checkout/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1
```

The developers behind `node-sass` are recommending to use `dart-sass` or `sass` instead as [`node-sass` is deprecated](https://sass-lang.com/blog/libsass-is-deprecated). These are drop-in replacements. However, when I tried to replace `node-sass` with one or the other, I hit a wall with sudden peer dependency version mismatches which prevented me from going further.

I imagine no one will be stocked about diving into `node-gyp` and peer dependency versions, but we need a volunteer! I've unfortunately wasted too much time going down the rabbit hole and can't do any more progress on this. Good luck to the brave soul who graciously takes on this task.

I will add that Node 16.18 is also the first LTS to officially support Apple Silicon processors (the current Node 14 requires emulation through Rosetta). Updating to Node 16 will hence significantly improve the experience for devs using M1/M2 Mac computers.

**Comment by bc-peng** [comment]
Thank you for making this post. 
We've noticed that Node 14's EOL is coming. Upgrading Node to 16 and beyond is undoubtedly in our TODOs.
cc @animesh1987

**Comment by loan-laux** [comment]
Just an update, LTS is now Node 18.

**Comment by animesh1987** [comment]
Hey @loan-laux we will be updating to node 16 soon first, and once that is stable will move to node 18.

**Comment by animesh1987** [comment]
Hey @loan-laux we have finished the work to update node version to 16. We will observe this for a few days before making the jump to v18. I am going to close this ticket for now. Thanks.
