### ISSUE TITLE
Npm dev build comman issue

### ISSUE THREAD

**Issue by talentedFullStack** [bigcommerce/checkout-js#1091]
Hello, I am customizing my bigcommerce store's custom checkout parts via this Checkout-js.
By the way, I see this error when I run "npm run build" command.
![image](https://user-images.githubusercontent.com/52531866/200635841-a051c518-6951-4325-8234-d604e278aaa9.png)

Please let me know about this issue reason. thanks your help.

**Comment by bc-peng** [comment]
Since we are doing `npm run build` nearly everyday on CI, the main branch should be able to build.
I see the error message is related to Git. Can you please try this command on a different branch or start from scratch?

**Comment by bc-peng** [comment]
Since we are doing npm run build nearly everyday on CI, the main branch should be able to build.
I see the error message is related to Git. Can you please try this command on a different branch or restart from scratch?

**Comment by talentedFullStack** [comment]
Different branch? I am first on Github. COuld you explain how to do this kindly again? thanks

**Comment by bc-peng** [comment]
Maybe you can fork https://github.com/bigcommerce/checkout-js and create your own branch.

Normally, `npm run build` will work after `npm ci`. Did you have other changes before getting the error message of the screenshot?

**Comment by talentedFullStack** [comment]
Yeah, I did run `npm ci` on my source localhost side before run '`npm run build`'

**Comment by talentedFullStack** [comment]
How to create my own Branch on this github source? Could you show me screenshot kindly?

**Comment by talentedFullStack** [comment]
Please see here. 
![image](https://user-images.githubusercontent.com/52531866/200692783-dd88c51f-ad95-4702-900c-0ab45fbb044d.png)

**Comment by talentedFullStack** [comment]
Now I already did `npm ci` on checkout-js source.  Already done successfully `npm ci`
But when run `npm run build` , I see that screenshot.

**Comment by talentedFullStack** [comment]
So I did click " Y" , after then I see this error. 
![image](https://user-images.githubusercontent.com/52531866/200693149-9a90b165-9eda-47d4-9189-fa7df70618df.png)

**Comment by bc-peng** [comment]
Alright, I see. Unfortunately, Windows env. does not meet the requirements for `checkout-js` that are listed here.
https://github.com/bigcommerce/checkout-js#requirements

**Comment by talentedFullStack** [comment]
Yeah, I see Unix-based operating system.
Can I do this on Mac laptop?

**Comment by talentedFullStack** [comment]
I mean Mac system.

**Comment by bc-peng** [comment]
Mac is OK. You should be able to build after `npm ci`.

**Comment by talentedFullStack** [comment]
Ok, let me try on Mac.

**Comment by fred33bondi** [comment]
Hello guys. I am running Windows 10. So it's the cause of this issue? Is there a workaround?

![image](https://user-images.githubusercontent.com/117710667/202406951-f9016f4a-3a07-43d3-af50-d37e57f43933.png)

**Comment by animesh1987** [comment]
Hey @fred33bondi you can try the solution from this issue https://github.com/bigcommerce/checkout-js/issues/767.
