### ISSUE TITLE
Missing imports

### ISSUE THREAD

**Issue by fred33bondi** [bigcommerce/checkout-js#1105]
![Screenshot 2022-11-14 195901](https://user-images.githubusercontent.com/117710667/201620148-23ef07dd-1e3b-4a8a-a2fa-0ece9d90b83e.jpg)

File does not exist. Even the folder "generated" does not exist. I just pulled the latest version today.

**Comment by animesh1987** [comment]
Hey @fred33bondi that particular folder is generated when we run the build using `npm run build`. 

Or if you just want to generate the folder without running the build you can run the following command `npx nx generate @bigcommerce/checkout/workspace-tools:auto-export --projectName=core`.

Hope this helps.

**Comment by fred33bondi** [comment]
> Hey @fred33bondi that particular folder is generated when we run the build using `npm run build`.
> 
> Or if you just want to generate the folder without running the build you can run the following command `npx nx generate @bigcommerce/checkout/workspace-tools:auto-export --projectName=core`.
> 
> Hope this helps.

@animesh1987 it fixed the issue. Thanks, much appreciated.
