### ISSUE TITLE
Guidline to integrate checkout on React/NextJS Application

### ISSUE THREAD

**Issue by Mubeen07** [bigcommerce/checkout-js#1108]
Hi @bc-peng & everyone,

I am having a web application in React/NextJS, which consuming storefront apis for data/products.

Now I'm having my own UI for checkout, but i want to utilize bigcommerce checkout sdk to achive the complete checkout functionality, so can someone help me how i can achive this without using the apis!

Thanks

**Comment by bc-peng** [comment]
To begin using your own UI, replace the natvie checkout with your own JS loader here. `{storeURL}/manage/settings/checkout`.

Then you can try with all of these `checkout-sdk-js` usages (https://github.com/bigcommerce/checkout-sdk-js#usage) to create your own checkout experience.

**Comment by bc-0dp** [comment]
Awesome! I'll close this one 🚀
