### ISSUE TITLE
Is there any way to run it in MAC OS ?

### ISSUE THREAD

**Issue by ChetnaSingh007** [bigcommerce/checkout-js#1119]
I am getting below error 
Node - v18.7.0
Npm - 8.15.0
Python 3.10.6

![image](https://user-images.githubusercontent.com/115691070/205568127-23dd73a0-939a-45e8-8481-6bf91b7e9a14.png)

![image](https://user-images.githubusercontent.com/115691070/205568213-fe023c12-6514-4440-8040-e4db95e34b54.png)

**Comment by animesh1987** [comment]
Hi @ChetnaSingh007 as you can see here https://github.com/bigcommerce/checkout-js/blob/master/package.json#L8 we support node v14 and npm v6 as of now. So can you try again with the above versions please.
