### ISSUE TITLE
process is undefined

### ISSUE THREAD

**Issue by GlobeProtocolNick** [bigcommerce/checkout-js#1159]
I'm currently trying to read some environment variables within the checkout but I can't seem to access my environment variable.
I have tried using REACT_APP_ as a prefix before the env, and it didn't work. Is this even possible, if yes, how should I do it?
![image](https://user-images.githubusercontent.com/112474574/212347682-34cffc79-ca1d-4fcd-b307-94ec472f4a35.png)

![image](https://user-images.githubusercontent.com/112474574/212346926-13855694-04c1-4534-9ca5-4808176a23cb.png)

**Comment by bc-peng** [comment]
You appear to be attempting to access ENV in a browser in the screenshot, which is unlikely because we produce a static HTML/CSS/JS bundle, which cannot possibly read ENV at runtime.

**Comment by GlobeProtocolNick** [comment]
Is there any way to inject these variables?
