### ISSUE TITLE
Failing unit test & test:core run NOT including .tsx spec files in circleci job

### ISSUE THREAD

**Issue by mikematrs** [bigcommerce/checkout-js#1219]
working from `1.296.0`

the test:core run fails at `src/app/customer/Customer.spec.tsx` -- Customer › when view type is "guest" › calls onUnhandledError if initialize was failed. (circleci job log attached)

This appears to be related to the recent addition to an if/guard statement that requires the `providerWithCustomCheckout` prop to be defined for the `initializeCustomer()` call. The prop is never passed to the mounted CustomerTest component in unit test so intializeCustomer() is never reached/called with the expected mocked rejection/error throw.

Seems this error was not caught due to circleci config only including .ts files instead of both .ts & .tsx files: `circleci tests glob "packages/core/**/*.spec.ts" | circleci tests split --split-by=timings` 

Unsure if 100% passing unit tests are out of scope and/or if only .ts files being included in circleci job is intended, but figured I raise a flag on this. Please feel free to close if deemed too low of priority/out of scope -- easy to resolve regardless.

Thanks for all the continued hard work on the SDK & checkout-js by everyone!

<img width="1229" alt="Screenshot 2023-03-09 at 2 14 26 AM" src="https://user-images.githubusercontent.com/114957211/223961073-ed055183-a156-49d5-88ec-899858072f56.png">

<img width="1042" alt="Screenshot 2023-03-09 at 1 47 50 AM" src="https://user-images.githubusercontent.com/114957211/223960092-2033083e-b406-424c-abb5-16fdf72193a2.png">

**Comment by animesh1987** [comment]
Hey @mikematrs thanks for reporting this. Have just merged the PR to fix this issue. Sorry for the inconvenience.
