### ISSUE TITLE
Mobile order summary modal is extra tall

### ISSUE THREAD

**Issue by aAdams01** [bigcommerce/checkout-js#1235]
The container on the order summary below about 500px has a large gap when expanded.

To reproduce, proceed to checkout and open the order summary:

![Screenshot 2023-03-29 at 3 59 44 PM](https://user-images.githubusercontent.com/99680748/228678230-9a85d4e4-1891-451b-a18d-d81014ebc7dc.png)

**Comment by animesh1987** [comment]
Hey @aAdams01 thanks for reporting this. Can you please provide more information on how to replicate this issue:
- Is it an issue in embedded checkout or native checkout?
- Does this happen on a particular mobile phone?

**Comment by aAdams01** [comment]
Hi @animesh1987,
We noticed this bug on native checkout. It is viewable on Android devices like the Pixel 6 Pro using the Chrome browser.

**Comment by animesh1987** [comment]
Hey @aAdams01 forgot to follow this up, we have rolled out some improvements to modal summary. Can you please confirm if this is still an issue for you? Thanks.

**Comment by aAdams01** [comment]
@animesh1987 looks like it is fixed! Thank you

**Comment by bc-0dp** [comment]
Closing as resolved 🙇
