### ISSUE TITLE
logout user from BigCommerce Store, If user is already logged out from eshop (developed in NextJS)

### ISSUE THREAD

**Issue by iamahmu** [bigcommerce/checkout-js#1241]
### Expected behaviour
User logged out from BigCommerce Store, If user somehow already logged out from eshop_(developed in NextJS)_. So when user try to navigate to checkout, he should be navigated to Checkout page as guest instead of Logged in user.

### Actual behaviour
Use somehow logged out from eshop, but still logged in on store when navigate to checkout from eshop as guest.

### Steps to reproduce behaviour 
I'm using this [api](https://developer.bigcommerce.com/api-docs/storefront/customer-login-api) to login user from our eshop web application developed in NextJS to BigCommerce store to navigate user on BigCommerce Native Checkout page.

My scenario is, if user some how logged out from our eshop but still having session on bigcommerce store how I can logout user from big commerce before navigating to checkout page as a guest (because user is not having session on eshop, so I don't have any user details).

`const logoutUrl = '{store}/login.php?action=logout'; const logoutWindow = window.open(logoutUrl, '_blank'); const checkLogout = setInterval(() => { logoutWindow?.close(); clearInterval(checkLogout); router.push('/checkout'); }, 3000);`

I tried this but in my opinion it's not a good approach. So, How i can logged out user from bigcommerce before navigating to checkout page as a guest from my eshop web application?

**Comment by animesh1987** [comment]
Hey @iamahmu is eshop a headless implementation?
Can you try using https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/core/src/customer/customer-request-sender.ts#L52 API for logout instead of the the php action. Thanks.

**Comment by iamahmu** [comment]
> Hey @iamahmu is eshop a headless implementation? Can you try using https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/core/src/customer/customer-request-sender.ts#L52 API for logout instead of the the php action. Thanks.

Hey @animesh1987 
Thank you for the response, but according to my understanding **checkout-sdk-js** is the implementation of checkout page, and we are not using the SDK in out NextJS headless application.

We are using mostly the v3 apis.

**Comment by animesh1987** [comment]
Checkout-sdk is an API wrapper for our storefront APIs.

I suppose you have a middleware API for our V3 APIs? Have you tried adjusting the redirect field of JWT as mentioned here https://developer.bigcommerce.com/api-docs/storefront/customer-login-api#signing-out ?

**Comment by bc-0dp** [comment]
Hi @iamahmu 
What you are describing here sounds like a headless implementation. The approach you are taking here would be the one I'd recommend as well. Currently the state is not shared between checkout/store and headless, but it is something we have on our radar. Feel free to create a feature request here: https://support.bigcommerce.com/s/ideas

**Comment by bc-0dp** [comment]
@iamahmu I am closing this for now, please feel free to open a new issue if it persists.
❤️
