### ISSUE TITLE
TranslatedHtml Should be used instead of TranslatedString

### ISSUE THREAD

**Issue by mattcoy-arcticleaf** [bigcommerce/checkout-js#1270]
In some cases, TanslatedHtml is used for elements coming from the en.json file. In other cases, TranslatedString is used.

I would advise TranslatedHtml be used for most (if not all) instances. It allows for adding HTML, and supports plain text strings just fine, simply adding customizability.

The particular example I am dealing with involves the translation key `guest_subscribe_to_newsletter_text`.

I set it as such: `"guest_subscribe_to_newsletter_text": "Please send me emails with tech news, product announcements, and sales. <a href=\"/privacy-policy\" target=\"_blank\">Privacy Policy</a>",`

I would expect the Privacy Policy text to be a link to the Privacy Policy page. Instead, the result is as follows:
<img width="640" alt="Screenshot 2023-05-10 at 11 38 45 AM" src="https://github.com/bigcommerce/checkout-js/assets/47044676/a6661abb-67b2-4305-982c-fc342179071c">

This would be fixed by simply changing TranslatedString to TranslatedHtml here: https://github.com/bigcommerce/checkout-js/blob/fd1684c71cd94dde78171f1fcd54b557998749b2/packages/core/src/app/customer/SubscribeField.tsx#L26

However, beyond this, I do believe there are more instances that should be changed.

**Comment by AndrewBarber** [comment]
Copying from the BigCommerceDevs Slack.

So it looks like:
`TranslatedString`: Simple string translation.
`TranslatedLink`: Takes an onclick event so you can bind a ‘link’ to a function as well as the string translation.
`TranslatedHtml`: Take the whole html element and renders it (include an a href) as well as the string translation.

I do agree with @mattcoy-arcticleaf here though, empowering developers by using `TranslatedHtml` in place of `TranslatedString` would mean we have more options for day-to-day fixes, without requiring a custom checkout to basically make a link. (Or the dreaded mutation observer route! 😱)

**Comment by bc-peng** [comment]
Thank you for bringing this to our attention.
Would you mind preparing a PR for this?

**Comment by funivan** [comment]
@bc-peng can we use TranslatedHtml instead of TranslatedString? 
If someone wants to use HTML tags in another phrase - they need to create an issue and wait for the release. WDYT about this idea?

**Comment by bc-peng** [comment]
> @bc-peng can we use TranslatedHtml instead of TranslatedString? If someone wants to use HTML tags in another phrase - they need to create an issue and wait for the release. WDYT about this idea?

I believe it should be judged on a case-by-case basis.
`TranslatedHtml` is a better fit for newsletter subscription.

**Comment by bc-0dp** [comment]
@mattcoy-arcticleaf @AndrewBarber should we close this one as completed?
