### ISSUE TITLE
I Run this code few days ago it's fine but when I clone updated repo 

### ISSUE THREAD

**Issue by Saadkc** [bigcommerce/checkout-js#1284]
![image](https://github.com/bigcommerce/checkout-js/assets/48367462/f5393ac8-5cc8-4a9d-a5a7-e4b17a74a183)

I got this issue how to resolved?

**Comment by animesh1987** [comment]
Hey @Saadkc are you seem to be using windows, so you might need a unix shell application. Or you can change the build command as per this post https://stackoverflow.com/questions/33188752/rm-is-not-recognized-as-an-internal-or-external-command-while-using-meteor-on

**Comment by Saadkc** [comment]
Thanks mate I fixed this using this.
![image](https://github.com/bigcommerce/checkout-js/assets/48367462/11bfc946-b3db-408a-9446-a0c18621742d)
