### ISSUE TITLE
Crash when Running

### ISSUE THREAD

**Issue by Saadkc** [bigcommerce/checkout-js#1285]
![image](https://github.com/bigcommerce/checkout-js/assets/48367462/2330f6e0-5231-4e3a-bbd1-ade20a4ab9e7)

Dist folder with files created after that it crashed. Is it okay 

if i run the command
npm run dev:server

yo host this and set my url to bigcommerce in custom checkoutjs url?

how can I linked and edit this Flow any recommendations?
thanks in advance

**Comment by bc-peng** [comment]
https://github.com/bigcommerce/checkout-js#development
Just replace the last step `npm run release:alpha` with `npm run dev:server` and serve `http://127.0.0.1:8080/auto-loader-dev.js`.

**Comment by Saadkc** [comment]
thanks it's closed
