### ISSUE TITLE
Question about dist folder

### ISSUE THREAD

**Issue by marekceglowski** [bigcommerce/checkout-js#1286]
Should the dist/ folder be in .gitignore? It is deleted and recreated when building each time. Or is there a purpose for it to be there in the repo?

**Comment by bc-peng** [comment]
In our CI pipeline, we include the `dist` folder in every release of `checkout-js`. This practice ensures that the necessary distribution files are readily available for deployment and usage. To illustrate this further, please refer to the following example: https://github.com/bigcommerce/checkout-js/issues/1286.

For your convenience, you can access and download any specific version of the checkout-js repository from our GitHub page, which offers a comprehensive list of tagged releases. Feel free to explore the available versions at: https://github.com/bigcommerce/checkout-js/tags.

**Comment by animesh1987** [comment]
Hey @marekceglowski adding from what Peng said, we don't want devs accidentally pushing their local dist folder hence we have added it to gitignore.
