### ISSUE TITLE
Support: npm ci failed for ubuntu22.04

### ISSUE THREAD

**Issue by yakiler** [bigcommerce/checkout-js#1300]
Execute "npm ci" command install depend unsuccess, "npm run build" generate dist dir loss auto-loader-<version>.js file.
![image](https://github.com/bigcommerce/checkout-js/assets/16573317/ce7ccd3f-5619-4ff9-83e1-f03526ffd61d)

**Comment by bc-peng** [comment]
We appreciate your input regarding `npm ci`. However, we kindly request that you provide us with an updated screenshot, as the current one does not seem to display any relevant errors.

**Comment by yakiler** [comment]
![image](https://github.com/bigcommerce/checkout-js/assets/16573317/b15609fd-2bbd-40e8-8807-8ae866b8aa21)
This is full log when execute "npm ci".
It looks like it was terminated.

**Comment by yakiler** [comment]
It works. Thanks
