### ISSUE TITLE
invalid_shipping_address

### ISSUE THREAD

**Issue by yakiler** [bigcommerce/checkout-js#1315]
Get invalid_shipping_address when call "/internalapi/v1/checkout/order" api.
"api/storefront/checkout/03cbdbb4-e15b-48ec-be6f-b7e7c0c9f152" get valid shipping address and billing address.

**Comment by yakiler** [comment]
When using custom checkout

**Comment by bc-peng** [comment]
Could you please refrain from utilizing the internal API and instead utilize the resources provided in our documentation?
You can find the necessary information at this link: https://developer.bigcommerce.com/docs/rest-storefront/orders#get-order

**Comment by bc-peng** [comment]
Could you please provide an overview of your efforts related to `/internalapi/v1/checkout/order`?
We would appreciate it if you could share the details of the request you made.
Thank you!

**Comment by animesh1987** [comment]
Also adding on from Peng, can you please share the address you might have used in your request. Thanks.

**Comment by yakiler** [comment]
`
fetch("https://orka-labs-inc.mybigcommerce.com/internalapi/v1/checkout/order", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Microsoft Edge\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-checkout-sdk-version": "1.381.4",
    "x-checkout-variant": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL29ya2EtbGFicy1pbmMubXliaWdjb21tZXJjZS5jb20iLCJpYXQiOjE2ODYxMDc4MTUsImRvbWFpbiI6eyJjYXJ0SWQiOiIwM2NiZGJiNC1lMTViLTQ4ZWMtYmU2Zi1iN2U3YzBjOWYxNTIiLCJjaGVja291dFZhcmlhbnQiOiJlbWJlZGRlZF9jdXN0b21fY2hlY2tvdXQifX0.R1FtA9b_Xev_NPhLCKCwz1aIs8QWnCnaWCfrRlbcQ8k",
    "x-xsrf-token": "2ab9fbd7c258354e309eeb6a1d699897595751c2245ad6546330174378717f47"
  },
  "referrer": "https://orka-labs-inc.mybigcommerce.com/embedded-checkout",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"cartId\":\"03cbdbb4-e15b-48ec-be6f-b7e7c0c9f152\",\"customerMessage\":\"\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
response:
{"status":400,"title":"Invalid shipping address","type":"invalid_shipping_address"}


fetch("https://orka-labs-inc.mybigcommerce.com/api/storefront/checkout/03cbdbb4-e15b-48ec-be6f-b7e7c0c9f152?include=cart.lineItems.physicalItems.options%2Ccart.lineItems.digitalItems.options%2Ccustomer%2Ccustomer.customerGroup%2Cpayments%2Cpromotions.banners", {
  "headers": {
    "accept": "application/vnd.bc.v1+json",
    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Microsoft Edge\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-checkout-sdk-version": "1.381.4",
    "x-xsrf-token": "2ab9fbd7c258354e309eeb6a1d699897595751c2245ad6546330174378717f47"
  },
  "referrer": "https://orka-labs-inc.mybigcommerce.com/embedded-checkout",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});


response: 
{"id":"03cbdbb4-e15b-48ec-be6f-b7e7c0c9f152","cart":{"id":"03cbdbb4-e15b-48ec-be6f-b7e7c0c9f152","customerId":0,"email":"y@h.com","currency":{"name":"US Dollar","code":"USD","symbol":"$","decimalPlaces":2},"isTaxIncluded":false,"baseAmount":0.01,"discountAmount":0,"cartAmount":0.01,"coupons":[],"discounts":[{"id":"70c37048-81db-4c64-9c49-c88ea594cc42","discountedAmount":0}],"lineItems":{"physicalItems":[{"id":"70c37048-81db-4c64-9c49-c88ea594cc42","parentId":null,"variantId":115,"productId":150,"sku":"US-OPD-NA-L","name":"US Open Domes (large)","url":"https:\/\/orka-labs-inc.mybigcommerce.com\/us-open-domes-large-\/","quantity":1,"brand":"","isTaxable":true,"imageUrl":"https:\/\/cdn11.bigcommerce.com\/r-4b20dad619e29ebf3490f7f35369a8220637ce48\/themes\/ClassicNext\/images\/ProductDefault.gif","discounts":[],"discountAmount":0,"couponAmount":0,"originalPrice":0.01,"listPrice":0.01,"salePrice":0.01,"retailPrice":null,"extendedListPrice":0.01,"extendedSalePrice":0.01,"comparisonPrice":0.01,"extendedComparisonPrice":0.01,"isShippingRequired":true,"giftWrapping":null,"addedByPromotion":false,"isMutable":true,"options":[]}],"digitalItems":[],"giftCertificates":[],"customItems":[]},"createdTime":"2023-06-05T08:21:48+00:00","updatedTime":"2023-06-07T03:19:16+00:00","locale":"en"},"billingAddress":{"id":"647d9bdf09d53","firstName":"fnn","lastName":"lnn","email":"y@ha.com","company":"cc2","address1":"702 Geraldine Lane","address2":"Lane","city":"New York","shouldSaveAddress":true,"stateOrProvince":"New York","stateOrProvinceCode":"NY","country":"United States","countryCode":"US","postalCode":"10004","phone":"917-954-6557","customFields":[]},"consignments":[{"id":"647d9c2e51fb7","shippingCost":0,"handlingCost":0,"couponDiscounts":[],"discounts":[],"lineItemIds":["70c37048-81db-4c64-9c49-c88ea594cc42"],"selectedShippingOption":null,"shippingAddress":{"firstName":"only2","lastName":"yeong","email":"","company":"custom","address1":"702 Geraldine Lane","address2":"Lane","city":"New York","stateOrProvince":"New York","stateOrProvinceCode":"NY","country":"United States","countryCode":"US","postalCode":"10004","phone":"646-358-3058","customFields":[],"shouldSaveAddress":true},"address":{"firstName":"only2","lastName":"yeong","email":"","company":"custom","address1":"702 Geraldine Lane","address2":"Lane","city":"New York","stateOrProvince":"New York","stateOrProvinceCode":"NY","country":"United States","countryCode":"US","postalCode":"10004","phone":"646-358-3058","customFields":[],"shouldSaveAddress":true}}],"orderId":null,"shippingCostTotal":0,"shippingCostBeforeDiscount":0,"handlingCostTotal":0,"taxTotal":0,"giftWrappingCostTotal":0,"coupons":[],"taxes":[{"name":"Tax","amount":0}],"subtotal":0.01,"grandTotal":0.01,"outstandingBalance":0.01,"isStoreCreditApplied":false,"shouldExecuteSpamCheck":false,"giftCertificates":[],"createdTime":"2023-06-05T08:21:48+00:00","updatedTime":"2023-06-07T03:19:16+00:00","customerMessage":"","channelId":1411901,"customer":{"id":0,"isGuest":true,"email":"","firstName":"","lastName":"","fullName":"","addresses":[],"storeCredit":0,"shouldEncourageSignIn":false},"promotions":[],"payments":[{}]}
`
"/api/storefront/checkout/id" can be obtained correctly billing address and shipping address

**Comment by yakiler** [comment]
When I use the same billing address, I get a new error: missing_email_address

**Comment by yakiler** [comment]
`
fetch("https://orka-labs-inc.mybigcommerce.com/api/storefront/checkouts/ef3a8654-f037-4ee9-be3c-5cd9b44a2c2b/billing-address?include=cart.lineItems.physicalItems.options%2Ccart.lineItems.digitalItems.options%2Ccustomer%2Cpromotions.banners", {
  "headers": {
    "accept": "application/vnd.bc.v1+json",
    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Microsoft Edge\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-checkout-sdk-version": "1.381.4",
    "x-xsrf-token": "2ab9fbd7c258354e309eeb6a1d699897595751c2245ad6546330174378717f47"
  },
  "referrer": "https://orka-labs-inc.mybigcommerce.com/embedded-checkout?setCurrencyId=1",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"email\":\"asdaa@asd.com\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
`
But i gave email in Customer Step.

**Comment by bc-peng** [comment]
Regarding order, we would like to inform you that we currently offer a single order endpoint use case, which is documented on our developer portal. You can find detailed information about it at the following link: [Get Order - BigCommerce Developer Documentation](https://developer.bigcommerce.com/docs/rest-storefront/orders#get-order).

Please note that the endpoint you are attempting to use is an internal one, `/internalapi/v1/checkout/order`, as indicated by its URL. We kindly request that you refrain from utilizing this endpoint and instead consider using the `checkout-sdk-js` library available at [GitHub - BigCommerce/checkout-sdk-js](https://github.com/bigcommerce/checkout-sdk-js). This library offers comprehensive functionality and will provide a more suitable solution for your requirements.

**Comment by yakiler** [comment]
I may have seen outdated docs, I'll switch checkout-sdk-js and try again, feel your help
