### ISSUE TITLE
How to pass parameters when open the checkout_url and receive them within a custom checkout app?

### ISSUE THREAD

**Issue by yakiler** [bigcommerce/checkout-js#1333]
I'm using a custom checkout to handle the checkout process, and I want users to be automatically logged in when they proceed to checkout after logging in on my website. I can append the user's email to the query of the checkout_url, but I'm not sure how to retrieve the email within checkout-js.
Any suggestions welcome, thanks a lot

**Comment by bc-peng** [comment]
The `checkout-js` conveniently shows a logged-in state for shoppers who have already logged in.
You might find it helpful to use BC's customer login API, https://developer.bigcommerce.com/api-docs/storefront/customer-login-api.

**Comment by animesh1987** [comment]
Hey @yakiler are you using checkout-sdk to build the custom app?

**Comment by yakiler** [comment]
@animesh1987  Yeah. Can I carry some data? when opening the checkout

**Comment by animesh1987** [comment]
If you use SDK, and if the shopper is already logged in you should be able to get customer details using https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/core/src/checkout/checkout-service.ts#LL737C30-L737C30

**Comment by yakiler** [comment]
@bc-peng I want to display a message when a user logs in to my website and proceeds to checkout on BigCommerce as a guest customer, using the same email address as on my website. It seems that when the user opens the address https://mybigcommerce.com/cart.php?action=loadInCheckout&id=2&token=0, it is still necessary to pass some additional parameters to complete the verification

**Comment by yakiler** [comment]
@animesh1987 Yes, I can. But I need to verify that the email address added by the shopper is the same as the one used on my website

**Comment by bc-0dp** [comment]
Are you looking for this:

https://developer.bigcommerce.com/api-docs/storefronts/guide/checkout

In conjunction with this
https://developer.bigcommerce.com/api-docs/storefront/customer-login-api

**Comment by yakiler** [comment]
@bc-0dp  Yes, but before that, I still need to obtain the user's login account on the a.com website, so that I can use it to complete automatic login on bigcommerce

**Comment by animesh1987** [comment]
I think now I am more confused with the request, let me try and summarise the workflow:

1. User is logged in on `a.com`
2. User is redirected to a BC checkout
3. We try to login the user automatically on checkout page load, using the email they logged in at `a.com`?

In this case how are we passing the email address?

**Comment by yakiler** [comment]
@animesh1987 Yes.It's feasible?
