### ISSUE TITLE
Google AddressSelector sometimes autofills the wrong city

### ISSUE THREAD

**Issue by egarrett** [bigcommerce/checkout-js#1390]
We utilize [Google Autocomplete for Addresses](https://support.bigcommerce.com/s/article/Address-Autocomplete?language=en_US) and we've recently discovered an issue that is causing some of our orders to come through  with an incorrect city in the shipping address. 

What seams to be happening is that for some municipalities, the  https://maps.googleapis.com/maps/api/place/js/PlaceService.GetPlaceDetails API returns the city in the `sublocality_level_1` address component, not the `locality` address component.  

To fix this, [AddressSelector.getCity()](https://github.com/bigcommerce/checkout-js/blob/09304e79c27c0d5d1312a697c915803c85347dae/packages/core/src/app/address/googleAutocomplete/AddressSelector.ts#L30) may need to be checking for the `sublocality_level_1` property and using that value if its set. 

You can reproduce this as follows:

1. While checking out, start typing in the following Canadian address: `1934 Montréal Rd, Gloucester, ON K1J 6N2`
2. When you see the auto suggestion for that address, select it to autofill.
3. After the autofill, you will see `Ontario` in the City field but it should be `Gloucester`.

**Comment by animesh1987** [comment]
Thanks for reporting this @egarrett, we will have a look at this in the coming weeks.

**Comment by bc-peng** [comment]
We might need to implement auto address filling rules for CA, similar to [what we did for the UK](https://github.com/bigcommerce/checkout-js/blob/09304e79c27c0d5d1312a697c915803c85347dae/packages/core/src/app/address/googleAutocomplete/AddressSelectorUk.ts#L4).

**Comment by animesh1987** [comment]
Fix released in https://github.com/bigcommerce/checkout-js/commit/88cced4fe3d5b9c2eeb9376fbca3b455d551e533.
