### ISSUE TITLE
Unused Lodash Imports

### ISSUE THREAD

**Issue by nowlena** [bigcommerce/checkout-js#1400]
It looks like there are files bringing in the entire lodash library but not using any of its utilities.

The files with the `import _ from 'lodash';`:

- `packages/core/src/app/payment/paymentMethod/AdyenV2PaymentMethod.tsx`
- `packages/core/src/app/payment/paymentMethod/AdyenV3PaymentMethod.tsx`

Can we either remove the import or at least reduce it to just the utility being used?

**Comment by bc-peng** [comment]
Thank you for bringing this to our attention.

**Comment by animesh1987** [comment]
@vitalii-koshovyi can you please take a look at this one.
