### ISSUE TITLE
Node Upgrade - Node 14 EOL

### ISSUE THREAD

**Issue by TheOrangePuff** [bigcommerce/checkout-js#1414]
Node 14 is now end of life: https://github.com/nodejs/release#release-schedule

The node version should be upgraded to an active version (ideally node 18 or higher).

**Comment by bc-peng** [comment]
Thank you for alerting us.

In March, we upgraded Node to 16; however, regrettably, we failed to include the `.nvmrc`. Now it has been updated.
- https://github.com/bigcommerce/checkout-js/pull/1234

We are aware that Node 16's EOL date has been advanced to this September. As a result, we scheduled an update to Node 18 for this month.
