### ISSUE TITLE
Whether the style and data validation of the checkout form can be set

### ISSUE THREAD

**Issue by gamlungJoeng** [bigcommerce/checkout-js#1458]
Form placeholder color of "Credit / Debit Card" same to default color, and missing validation

**Comment by animesh1987** [comment]
Hey @gamlungJoeng is the request to change styles for forms? What payment provider are you using?

**Comment by gamlungJoeng** [comment]
It's Affirm and Stripe @animesh1987

**Comment by animesh1987** [comment]
I think they have their own hosted forms, so I doubt we have ways to change the styles 🤔 Unless you can get in the CSS side of things.

**Comment by gamlungJoeng** [comment]
Does the payer provide an interface, such as passing some third-party style sheets in the iframe to override certain styles? If not, can we ask them to provide similar functions?

**Comment by animesh1987** [comment]
Hey @gamlungJoeng it will be a nice to have, but I suppose not something we have plans for at the moment. We can come back to this as an enhancement in future.
