### ISSUE TITLE
Watch not working on local development

### ISSUE THREAD

**Issue by matthewdolman** [bigcommerce/checkout-js#1487]
The instructions [here](https://developer.bigcommerce.com/stencil-docs/customizing-checkout/open-checkout-quick-start) state:

> Start webpack in watch mode and launch dev server.
> `npm run dev & npm run dev:server`

However when I do this and make changes to files in `packages/core/app` there doesn't seem to be any change detection occurring, am I missing something?

**Comment by animesh1987** [comment]
Can you just try with using `npm run dev`?

**Comment by matthewdolman** [comment]
This also does not watch for changes

**Comment by animesh1987** [comment]
We haven't seen these issues locally, can you please give more details about the environment.

**Comment by matthewdolman** [comment]
Sure

I am running in WSL Ububtu 20.04
Node: 18.17.1
NPM: 9.6.7

After `npm ci` I run `npm run dev`, webpack compiles, however when I make a change to the files therte is not the expected recompile, the terminal doesn't move.  I can stop and rerun `npm run dev` but this is taking a few mins and so is not ideal.

**Comment by matthewdolman-afd** [comment]
Any feedback on this?

**Comment by matthewdolman** [comment]
Any feedback on this?

**Comment by Shmulyitz** [comment]
Same issue, any update?

**Comment by matthewdolman-afd** [comment]
My issue seemed to be that I was running it on windows and it was super slow.  I started running it on WSL2 and the initial compile was faster and it did watch and rebuild, but the output still does not change and so in my case I have to wait about 5 seconds and the change would be reflected in the checkout.

It would be nice if the docs had a warning about how slow it runs on windows and to advise people to run it on WSL.

**Comment by animesh1987** [comment]
Thanks for the update @matthewdolman-afd, we will update the docs accordingly to reflect the state of things.

**Comment by bc-0dp** [comment]
https://github.com/bigcommerce/checkout-js/pull/1696

Can close

**Comment by zachadams16** [comment]
was the fix for this to use wsl version 1 instead of 2?

**Comment by matthewdolman** [comment]
I use WSL 2.  It is worth mentioning that on my terminal at least it is very difficult to actually see that it has updated, the only thing that changes on a rebuild is the milliseconds following the decimal point in the build time.  So if you are expecting something more explicit, like what you might see on other systems, where you get a new scrolling message on each rebuild you might miss it but it has in fact run.
