### ISSUE TITLE
How To Manage Gift certificate form Data In  Checkout JS ?

### ISSUE THREAD

**Issue by Kaushik-d44** [bigcommerce/checkout-js#1504]
Hello @bc-peng  @animesh1987 

I have Installed [checkout-js](https://github.com/bigcommerce/checkout-js) in my local Environment 

Now I add Some Product In cart and Go to checkoutpage 
I need to add Some Custom functionality With JS or PHP side Code when Apply Gift certificate before Submit Form 
Actually Need to check Applied gift certificate part of List with Thirdparty Plateform API
I have Already managed On cart page Need To manege This on Checkout page 

its Also usefull If any webhook Provided 

Thanks In Advance

**Comment by bc-peng** [comment]
We are using `checkout-sdk-js` to apply coupon and gift certificate in `checkout-js`.
https://github.com/bigcommerce/checkout-sdk-js#apply-coupon-or-gift-certificate
For your case, your custom JS code just needs to be invoked before this line.
https://github.com/bigcommerce/checkout-js/blob/99cef5d41f2bc1128c0326255f4c719ffe2ad3b6/packages/core/src/app/cart/Redeemable.tsx#L207

**Comment by Kaushik-d44** [comment]
Thanks @bc-pen its Working For me !
