### ISSUE TITLE
CORS Error When Called POST  method API In checkout Page 

### ISSUE THREAD

**Issue by Kaushik-d44** [bigcommerce/checkout-js#1510]
Hello @bc-peng @animesh1987 Good Afternoon, 

I have Setup Custom **Checkout-js** In My local Environment 
As per My Previous Isuue I want To Add Some Custom Functionality When Giftcard Apply On Checkout page 
I Already Developed This Functionality On **Cart.php**

Added Following Code Before Giftcard Apply In this Function Diffrent API called To check Validation Of Entered Giftcard : 

         ` let isValidinT1 = checkIsGiftCertValidT1(code);
                console.log(isValidinT1);

                if(isValidinT1.status == true) //check Entered giftcard Exist In Trident T1 Or Not 
                {
                    CheckGiftCardInBigcomm(code) .then((returnValue) => //Check Entered Giftcard exist In Bigcommerce Store Or Not 
                    {
                        console.log(returnValue.status);
                        if(returnValue.status == "failed")
                        {
                            
                            createGiftCardinBigCommerce(isValidinT1.data, code).then((gifcardCreate) => 
                            {
                                console.log(gifcardCreate);
                                if(gifcardCreate){
                                   // applyCoupon(code);
                                }
                            })

                        }else
                        {
                            var bigcommerceData = returnValue.data;
                            var gifcardCreate = updateGiftCardinBigCommerce(isValidinT1.data,bigcommerceData,code);
                            console.log(gifcardCreate);
                           
                        }
                    })
                    .catch((error) => {
                      console.error('Error in checkGiftCardInBigcomm:', error);
                    });

                }else{
                    alert('Invalid In Trident T1');
                }
                await applyGiftCertificate(code); `
                
 
 Isuue Is : 
 When I call API with GET method Its Working Fine 
But for POST method It Will Abort With CORS Error 

![image](https://github.com/bigcommerce/checkout-js/assets/139958216/15b36f75-f18e-4294-bdd0-0550843b07a4)

Code File : 
https://codefile.io/f/839OS4vQ3c
https://codefile.io/f/vgHHabAeAX

Same API Working In cartpage fine 

![image](https://github.com/bigcommerce/checkout-js/assets/139958216/8af4fdb0-eb75-46eb-b7a8-3b89ea040567)

Thanks In Advance

**Comment by bc-peng** [comment]
CORS problems are typically handled on the server side.
The server (`TridentData.API_URL`) must be configured to contain the relevant CORS headers.
These headers inform the browser that requests from particular domains are allowed.

**Comment by Kaushik-d44** [comment]
@bc-peng 

Thank you For Your support 

CORS problems are typically handled on the server side.
The server (TridentData.API_URL) must be configured to contain the relevant CORS headers.
These headers inform the browser that requests from particular domains are allowed.
 
=> I understand CORS problems are typically handled on the server side But Its already working Fine On cart page if problem with serverside than Also should not work there 
Cart page Link : https://johnsgunstore.mybigcommerce.com/cart.php

As per screenshot 
![image](https://github.com/bigcommerce/checkout-js/assets/139958216/5201db38-ed44-4f13-8d78-a0609023113a)

**Comment by bc-peng** [comment]
Perhaps we can disable CORS on your server and test the checkout page to see if it is a server-side issue.

**Comment by Kaushik-d44** [comment]
ok How can I disabled It 

Can i From Bigcommerce Admin Panel ?
Or By Code ?

**Comment by bc-0dp** [comment]
@Kaushik-d44 
Just following up here, did you resolve this?

You would have to disable this on your end, from where you host and serve the checkout files from. Typically you'd see this in a server_block for Nginx or VirtualHost on Apache. How specifically, would depend on how the files are being served from your side. 🙇

**Comment by Kaushik-d44** [comment]
I have Resolved It by Update allow all method on server side 

```
header('Access-Control-Allow-Origin: *');  // Allow requests from any origin
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');
```

**Comment by bc-0dp** [comment]
Amazing @Kaushik-d44 !

Happy you got it to work. I'll close this issue as completed.
🚀
