### ISSUE TITLE
Console has an error of ReferenceError after add avatax sdk 

### ISSUE THREAD

**Issue by yakiler** [bigcommerce/checkout-js#1566]
I add avatax library on master,then start up the checkout. The shipping address section cann't expand, Then i open devtools found the console panel show ReferenceError. But has no error on terminal.
![image](https://github.com/bigcommerce/checkout-js/assets/16573317/928886ed-12eb-449b-be6b-25e3317d99e8)
![image](https://github.com/bigcommerce/checkout-js/assets/16573317/be2fcc52-41d9-4387-a3c0-cf4ee8e1dbfa)

**Comment by yakiler** [comment]
I use the library of "["avatax": "^23.8.1",](https://github.com/avadev/AvaTax-REST-V2-JS-SDK.git)" is release 23.8.1

**Comment by bc-peng** [comment]
Could you please list all actual changes you have made to `checkout-js`?

**Comment by yakiler** [comment]
I switch to master branch and pull origin, then install the avatax library. So no changes on checkout-js

**Comment by yakiler** [comment]
![image](https://github.com/bigcommerce/checkout-js/assets/16573317/d638a470-08e4-438e-ac45-069aa7e168ff)
I add the validate address in Shipping.tsx when submit the shipping form.
![image](https://github.com/bigcommerce/checkout-js/assets/16573317/0583407e-2c7e-4a1f-b51b-c97c3fcbc882)
The validateAddress detail same to this

**Comment by yakiler** [comment]
This lib only runs on the server env.
This error is missing Buffer Object.
