### ISSUE TITLE
Error in store checkout page when running checkout-js from local

### ISSUE THREAD

**Issue by xy-work** [bigcommerce/checkout-js#1695]
Hi,

We are trying to explore the custom checkout route and in the settings, we have enter this script URL: http://127.0.0.1:8080/auto-loader-dev.js after running the solution. 

On the checkout page, we are encountering the following error.

![2024-02-13 14 14 20- 30725](https://github.com/bigcommerce/checkout-js/assets/89173436/ec5948d9-77b7-451e-91de-de447a4d516c)

We have also tried http://127.0.0.1:8080/auto-loader.js, but the file seems to be the exact same as the one with the dev suffix, and both look very different from the default loaded js (https://cdn11.bigcommerce.com/shared/microapp/checkout/dist/loader-1.441.2.js) 

Browser: Edge / Firefox
Node: v18.18.0
npm: v9.8.1

**Comment by bc-0dp** [comment]
Hi @xy-work 

Can you check if you're correctly running `npm run dev` and `npm run dev:server` to serve the file?

**Comment by xy-work** [comment]
@bc-0dp yes, it is running. 

I'm unable to run both the commands at once for some reason, but I ran it serially. 

localhost:8080 shows the files in the build dir as mentioned in the page
![2024-02-13 18 18 37- 54654](https://github.com/bigcommerce/checkout-js/assets/89173436/7f7a9079-834a-4946-b72f-0eaef2f767c1)

**Comment by bc-0dp** [comment]
@xy-work thanks for verifying.

Would you be able to execute the commands and try from WSL?

According to this thread, https://stackoverflow.com/questions/65293577/uncaught-typeerror-is-not-a-function-in-core-js
others have experienced 'similar' issues executing the commands from command prompt/powershell

**Comment by bc-0dp** [comment]
also see this thread: https://github.com/bigcommerce/checkout-js/issues/753

**Comment by xy-work** [comment]
Thanks @bc-0dp . I'm still getting the same error unfortunately. I have tried removing the `node_modules` and `build` folder, and then redid all the npm steps, but still to no avail.

**Comment by bc-0dp** [comment]
good luck! Cheering for your success

**Comment by xy-work** [comment]
Managed to get it to work, thanks a lot @bc-0dp!!
