### ISSUE TITLE
Order Summary option label and value should be visually separated

### ISSUE THREAD

**Issue by mattcoy-arcticleaf** [bigcommerce/checkout-js#1700]
When you add an item to cart with options and reach the checkout, the order summary shows the option label and value on a single line in a single HTML element with no separation. This can be very confusing to customers. These should be separated by a colon, or at least placed into separate HTML tags so a developer can style them differently.

#### Current implementation:
<img width="412" alt="Screenshot 2024-02-15 at 9 00 37 AM" src="https://github.com/bigcommerce/checkout-js/assets/47044676/91f67663-2544-492e-ab38-13e85047e9d2">
<img width="762" alt="Screenshot 2024-02-15 at 9 02 54 AM" src="https://github.com/bigcommerce/checkout-js/assets/47044676/b1f3dac5-b321-46ad-9f1f-9b27104857d9">

#### Proposed implementation 1:
<img width="764" alt="Screenshot 2024-02-15 at 9 16 43 AM" src="https://github.com/bigcommerce/checkout-js/assets/47044676/cae0c583-47c4-471a-8876-d30cba147de7">
<img width="394" alt="Screenshot 2024-02-15 at 9 16 47 AM" src="https://github.com/bigcommerce/checkout-js/assets/47044676/ea5f2dae-455f-47bf-a075-4977010a682e">

#### Proposed implementation 2:
<img width="768" alt="Screenshot 2024-02-15 at 9 18 05 AM" src="https://github.com/bigcommerce/checkout-js/assets/47044676/ebdbf5dd-a9fa-46c4-913b-9b06b7b65491">
<img width="415" alt="Screenshot 2024-02-15 at 9 18 08 AM" src="https://github.com/bigcommerce/checkout-js/assets/47044676/5e38db40-972c-4730-b412-b8a1c514626e">

**Comment by bc-0dp** [comment]
That's cool!
As a minimum split them up in option value spans.

**Comment by developerscott** [comment]
This would be super helpful to us and our clients as well. 
I prefer option 2 (to start) as it gives us more control than option 1.

**Comment by animesh1987** [comment]
Sounds like a nice improvement, we will go with option 2.
