### ISSUE TITLE
Tracking with Enhanced Ecommerce in Google

### ISSUE THREAD

**Issue by gucampana** [bigcommerce/checkout-js#1774]
Hey guys, just wanted to know how if the enhanced tracking is supported, if so how it should be implemented to track the conversion for orders correctly?

Thanks

**Comment by animesh1987** [comment]
Hey @gucampana can you please explain what you mean by enhanced tracking and the context.

**Comment by gucampana** [comment]
Hi @animesh1987, sorry we have been asked to complete this task around tag manager / analytics, apologies if my first question was confusing. 

Basically, we are trying to figure it out how to enable "Enhanced Conversion" (https://support.google.com/google-ads/answer/13262500?hl=en#validate_implementation) on a optimised one-page checkout confirmation page. 

Facebook and GA tracking are handled by BigCommerce integrations, and we would like to know if there is a supported way to also implement "Enhanced Conversion".

If there is no built way to do that, would be possible/advised to load GTM on confirmation page (via script manager) and implement that ourselves? If went on this route, is there any documentation on how to get the data from the current page/transaction?
