### ISSUE TITLE
Not Watching for code changes

### ISSUE THREAD

**Issue by zachadams16** [bigcommerce/checkout-js#1899]
When I run the code and make a change, its not hot rebuilding the code and showing the change I made. I remember it use to work like this when I developed a custom checkout 2 years ago, is there something I have to set up to get it to hot reload when developing locally?

**Comment by zachadams16** [comment]
seems like i have to run on wsl 1 not 2

**Comment by bc-peng** [comment]
I'm using hot rebuilding now.
The command is `npm run dev`. In addition, serving `checkout-js` with `npm run dev:server` from the URL, `http://127.0.0.1:8080/auto-loader.js`.

**Comment by zachadams16** [comment]
yep, i was using the -dev.js

**Comment by mitesh-avid-brio** [comment]
hey it's still not hot-reloading @zachadams16  did you figure out something?
