### ISSUE TITLE
Registering a new user clears all my consignments

### ISSUE THREAD

**Issue by zachadams16** [bigcommerce/checkout-js#1904]
I made a custom cart which creates consignments and allows the user to ship to multiple addresses. When I go to checkout and register a new user, all my consignments get cleared. It keeps the cart contents but my consignments get cleared. It works if I sign into an already existing account, as it copy's all the consignment overs but not when registering a new user.

**Comment by animesh1987** [comment]
Hey @zachadams16 sorry for the late response on this one. This is expected behaviour as with a new user there are different rates that need to be applied plus there is complications around customer group and addresses.
