### ISSUE TITLE
Apple Pay is not showing up in the checkout page

### ISSUE THREAD

**Issue by fathiabdulrahim** [bigcommerce/checkout-js#1973]
Hi , I am trying to make Apple Pay showing up in the checkout page that I have

I have enabled `apple-pay` option in settings->payment methods page

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/1772a027-f9e7-49d7-a325-31a312fb6050">

And I am using the latest code from master `v1.520.1` 

But i am not seeing apple pay options in the checkout page

<img width="861" alt="image" src="https://github.com/user-attachments/assets/f5316772-2c28-49f5-addb-feee53b13f75">

Am i missing any steps here ?

**Comment by animesh1987** [comment]
Hey @fathiabdulrahim naive question are you using safari?

**Comment by fathiabdulrahim** [comment]
@animesh1987 im testing using chrome , does it work in safari ?

**Comment by fathiabdulrahim** [comment]
@animesh1987 , thanks man , i can see it now by using Safari browser
<img width="706" alt="image" src="https://github.com/user-attachments/assets/866aaf0c-1969-4368-85f9-9d0b00e22cc2">
