### ISSUE TITLE
Updating .scss Stylesheet During Development Breaks Script Integrity

### ISSUE THREAD

**Issue by hunterashaw** [bigcommerce/checkout-js#2061]
When running `npm run dev` & `npm run dev:server` (and store is pointed to local checkout), after editing a .scss file (for instance `_checkoutHeader.scss`) and refreshing the checkout page, the script integrities break, requiring the dev server to be restarted.

I temporarily resolved this by turning off integrities on the webpack config when not in production, but it's still producing a non-blocking error.

**Comment by animesh1987** [comment]
Thanks for reporting this @hunterashaw , we will have a look at this in the next couple of weeks.

**Comment by bc-peng** [comment]
We’ve released a feature that allows you to bypass the integrity hash values in the local development environment.
You could get it by rebasing your code to the latest master.
