### ISSUE TITLE
This string is no longer reading from our local en.json file.

### ISSUE THREAD

**Issue by joshuamil** [bigcommerce/checkout-js#437]
https://github.com/bigcommerce/checkout-js/blob/ef7ae8d75446f7f1eaf7892d9198b2771b4bfb6e/src/app/cart/Redeemable.tsx#L59

The value for "reedemable.toggle_action" in our "en.json" file reads: "Enter Discount / Coupon Code"
The production website reads: "Coupon/Gift Certificate"

We do not offer Gift Certificates, we have that functionality overridden. However, the Production Site is pulling a different value that we haven't set.

**Comment by capsula4** [comment]
Those values in checkout serve as a default value, but ultimately they are overriden by the theme language files if they exist.

https://medium.com/bigcommerce-developer-blog/the-complete-guide-to-checkout-customization-on-bigcommerce-6b566bc36fa9

> 3. Multi-language checkout.
Moving on to customizations that require light custom code, the text strings that display on the Optimized One-page Checkout page can be edited, or even translated into multiple languages.

The checkout page follows the same convention used by all Stencil templates to render text strings. The {{lang}} helper, custom to Stencil, pulls a text string’s value from a set of JSON files, based on the language setting detected in the shopper’s browser. A store can have multiple .json lang files, one for each language that a store supports.

To access the translation keys that are rendered on the checkout page, you’ll need to append a JSON object containing the checkout keys and their text string values to your store’s .json lang file(s). If English is the default language on your store but you wish to change the wording on some of the checkout fields, you would add the checkout JSON object to the en.json file; if your store supports English and French and you wish to show a French version of the checkout page to French-speaking shoppers, you would add the checkout JSON object to your fr.json file and translate the key values accordingly.
