### ISSUE TITLE
code ELIFECYCLE errno 2

### ISSUE THREAD

**Issue by Ankit-Rapidops** [bigcommerce/checkout-js#439]
I have got the error when I fire the command npm run build. I have tried many times to clean npm cache but it still gets the error. Can you please help me to solve this issue? Here is the below error code.

    [171] (webpack)/buildin/module.js 552 bytes {0} {1} [built]
    [174] ./src/app/common/bundler/index.ts 71 bytes [built]
    [175] ./src/app/common/utility/index.ts 180 bytes [built]
    [176] ./src/app/auto-loader.ts 1.31 KiB {0} [built]
    [177] ./src/app/common/utility/emptyData.ts 276 bytes [built]
    [178] ./src/app/common/utility/parseAnchor.ts 396 bytes [built]
    [179] ./src/app/common/utility/retry.ts 1.26 KiB [built]
        + 171 hidden modules
     npm ERR! code ELIFECYCLE 
     npm ERR! errno 2
     npm ERR! @bigcommerce/checkout@1.93.0 build: `rm -rf dist && webpack --mode production`
     npm ERR! Exit status 2
     npm ERR!
     npm ERR! Failed at the @bigcommerce/checkout@1.93.0 build script.
     npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

     npm ERR! A complete log of this run can be found in:
     npm ERR!     C:\Users\rapidadmin\AppData\Roaming\npm-cache\_logs\2020-10-19T10_21_38_252Z-debug.log

**Comment by capsula4** [comment]
What version of `npm` and `node` are you using?

**Comment by JKarlavige** [comment]
@capsula4 I am receiving this as well on both node versions 10.16 and 12.18.3. If I scroll up a bit in the errors, I get the following:
`ERROR in ./src/scss/App.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: $ is not a function
`
Also worth noting that i'm on Windows and the build script does not work out of the box for Windows, as 'rm' is not a recognized command. I updated this to `rmdir /Q /S dist && webpack --mode production`, but not sure if there's anything else that would prevent the build from processing on Windows.

**Comment by capsula4** [comment]
Unfortunately, our code and build instructions have not been tested on Windows. I recommend using a UNIX system for this. You may be able to look for UNIX emulators for Windows but cannot guarantee how well they would work.
