### ISSUE TITLE
navigateToOrderConfirmation generate invalid redirect

### ISSUE THREAD

**Issue by mikhail-khalizev** [bigcommerce/checkout-js#446]
Situation: I am now at `https://***/embedded-checkout/?setCurrencyId=2` page.

And after calling `navigateToOrderConfirmation` it redirects to `https://***/embedded-checkout/?setCurrencyId=2/order-confirmation`. What is wrong. Must be `https://***/embedded-checkout/order-confirmation/?setCurrencyId=2`

**Comment by mikhail-khalizev** [comment]
File link: https://github.com/bigcommerce/checkout-js/blob/master/src/app/checkout/navigateToOrderConfirmation.tsx

**Comment by davidchin** [comment]
Thank you for raising this issue. We've created an internal ticket to track this issue: CHECKOUT-5300.
