### ISSUE TITLE
cdn css overrides styles in forked repository

### ISSUE THREAD

**Issue by ManrickCapotolan** [bigcommerce/checkout-js#462]
Description

When we are running `npm run build` and attach it to the store, the styles are being overwritten by the styles coming from this url: https://cdn11.bigcommerce.com/shared/microapp/checkout/dist/checkout-756acae0.css.

Is there a way to disable loading of this file and just use the css that is built out of our repository?

**Comment by capsula4** [comment]
Hey Manrick,

Are you using our recommended way for installing a Custom Checkout via Control Panel? If not, please read the following documentation https://developer.bigcommerce.com/stencil-docs/customizing-checkout/installing-custom-checkouts

**Comment by dougep** [comment]
Please feel free to reopen the issue or contact us again if you have further issues.
