### ISSUE TITLE
There's a compile error '$ is not a function'

### ISSUE THREAD

**Issue by Mackkkk** [bigcommerce/checkout-js#485]
How could I run dev in Windows?

![image](https://user-images.githubusercontent.com/24667744/102745519-208a7680-4397-11eb-9a6d-83ec8d34302d.png)

**Comment by Mikhail-MM** [comment]
I don't really think this repo works on Windows/Non Unix systems. The build step always failed for me.

**Comment by capsula4** [comment]
Hi Mackkkk,

As listed in the requirements page https://github.com/bigcommerce/checkout-js#requirements, this repository work on an unix-based system. You might want to look into using a unix console for windows.

**Comment by arosesiejdev** [comment]
Is there any workaround for this or recommendations on steps to using a Unix console on Windows?

**Comment by bc-peng** [comment]
For Unix cole on Windows, think you might want to look into something called `windows subsystem for linux`. 

I've found a doc from MS on https://docs.microsoft.com/en-us/windows/wsl/install.
> This guide will show you how to install a Linux distribution (such as (Ubuntu, OpenSUSE, Kali, Debian, Arch Linux, and more) using the Windows Subsystem for Linux. WSL enables you to use Linux tools, like Bash or Grep, completely integrated with Windows tools, like PowerShell or Visual Studio Code, with no need to dual-boot.

Also, would you mind closing the new issue because it is eactly the same as this one?
