### ISSUE TITLE
shouldSubscribe checkbox not staying checked

### ISSUE THREAD

**Issue by AndrewBarber** [bigcommerce/checkout-js#518]
### Expected behavior
'Subscribe to newsletter' checkbox should stay checked throughout filling in checkout fields.

### Actual behavior

'Subscribe to newsletter' checkbox becomes unchecked when moving to the next section of the form.

### Steps to reproduce behavior
1. Enter an email address.
2. Tick the checkbox to subscribe to the newsletter.
3. Click checkout as a guest.
4. Once shipping is highlighted click on Edit from the first step (Customer).
5. The newsletter checkbox is no longer checked.

**Comment by AndrewBarber** [comment]
![Screen Recording 2021-02-19 at 10 55 00](https://user-images.githubusercontent.com/135927/108495943-54075580-72a1-11eb-82f5-3a974aaa32e0.gif)

**Comment by capsula4** [comment]
That's a good suggestion. However, the newsletter subscription happens as soon as the shopper continues as a guest.

If the checkbox remained marked as suggested, but then manually unchecked by the shopper, it might set the expectation that then I would be unsubscribing from the newsletter. At the moment it's designed to maximize the newsletter subscriptions, and unsubscribe can only happen via the "account settings" page or "unsubscribe" link in any received email.

**Comment by bc-0dp** [comment]
Hey @AndrewBarber 
would you be ok if we close this?

I concur with Luis, when navigating back to the customer step we must assume it's to change the email address, as such we would probably be required to request a new consent for newsletter subscription. WDYT?

**Comment by AndrewBarber** [comment]
I understand this interaction and decision now, so happy to close as an overall. 

Though I do feel, if this is the case, the better interaction would be that IF the email address is modified, then untick the newsletter box. 

Just my 2 pennies worth! 😂

**Comment by bc-0dp** [comment]
Your feedback is always very appreciated and PR's are always welcome 🚀 

Will close this for now then.

Thanks Andrew ❤️

**Comment by animesh1987** [comment]
Thanks for restarting this discussion, we have been recently evaluating our discussions on this topic. There are a coupe of bugs in our backlog that we are actively triaging, once we resolve those bugs we might get a more consistent experience. 

Although it might not be as straightforward as there are quite a few moving pieces, but we are looking at this issue actively.
