### ISSUE TITLE
Issue clicking continue from step 2 to 3 after customizing

### ISSUE THREAD

**Issue by creativereason** [bigcommerce/checkout-js#596]
Seeing the issue [here](https://github.com/bigcommerce/checkout-js/blob/7e5c73d233b7a6c2d7976c284d5a22b64895b475/src/app/shipping/Shipping.tsx#L184-L190) 

This code looks the same in the current github library as it does in ours. Here’s what we are encountering in a nutshell:
 
Before the code I link to above runs, we call some remote APIs that have await on them, which work and then forces a Checkout refresh to show those on the optimized checkout. So we call
`await this.props.checkoutService.loadCheckout();
` 
What we are seeing is inconsistent behavior from the Continue button on step 2:
- Sometimes it continues to step 4 (which makes sense because our tests have “Same as billing address” checked.
- Sometimes it doesn’t continue, it fires and seemingly times-out (with no errors in console that indicate what happened, in those cases, click continue again works fine).
- Sometimes it moves to step 3 (which makes no sense, because the billingSameAsShipping parameter is true when we test that) on this call:          
`navigateNextStep(billingSameAsShipping);`

**Comment by bc-0dp** [comment]
@creativereason was this resolved?

**Comment by animesh1987** [comment]
Closed due to inactivity.
