### ISSUE TITLE
Digital wallets as express checkout

### ISSUE THREAD

**Issue by pinktonio** [bigcommerce/checkout-js#685]
It would be nice to have digital wallets including Apple Pay as an express checkout option at the beginning of the checkout process like Shopify does it. That way the other checkout steps could be skipped. It would also support headless solutions better where the embedded checkout is used and Apple Pay currently can't be accessed.

**Comment by TomA-R** [comment]
Thanks for the suggestion! We're currently exploring adding ApplePay to the checkout, but the first iteration of this will just be as a payment method in the accordion at the bottom of the page (so you'll be able to use your stored cards but it won't have the express checkout experience). That will likely be delivered in the next few months. We'll explore adding this as an option at the top of the checkout afterwards, but there's no timeline/commitment for it yet. We'll update you once we know more.

**Comment by TomA-R** [comment]
Hey @pinktonio,

ApplePay has been added as an option at the top and at the bottom of the checkout. The button at the top is the "express" experience where the shopper's ApplePay details are used to populate the shipping and billing addresses, and fetch shipping quotes.

<img width="639" src="https://user-images.githubusercontent.com/1606901/164873405-58d1b206-a998-4fbf-aad7-4d56ccdaccb7.png">

The option at the bottom of the checkout uses details entered into the checkout by the shopper.

<img width="639" src="https://user-images.githubusercontent.com/1606901/164873407-1dde1162-3357-4806-b538-880d2fbbf158.png">

In case you try it out, any feedback is welcome!

**Comment by pinktonio** [comment]
Awesome! Thanks for the update. I'll check it out.

**Comment by fathiabdulrahim** [comment]
Hi @TomA-R , i saw you got it working with ApplePay , could u help me with my issues here https://github.com/bigcommerce/checkout-js/issues/1973 ?

**Comment by TomA-R** [comment]
Seems like @animesh1987 helped out with #1973, let us know if you run into any other issues!
