### ISSUE TITLE
Step headers styling is now broken with larger header fonts

### ISSUE THREAD

**Issue by mattcoy-arcticleaf** [bigcommerce/checkout-js#703]
We have noticed that some of our clients' stores now have some styling issues with the step headers on the checkout. This seems to be a common occurrence on any site where we increased the font size of the step headers. 

#### Example
<img width="825" alt="Screen Shot 2021-09-21 at 4 16 57 PM" src="https://user-images.githubusercontent.com/47044676/134260375-b294e152-452b-473b-bc8a-1ab8193cec16.png">

I believe this was introduced in the following commit: https://github.com/bigcommerce/checkout-js/commit/1f14515b74b282589419986a2a52673ec80e61f9

I believe the root cause is that for some reason the height attribute on the figure is setting the height of the step header, resulting in a broken look when the header font is larger than the set height. Perhaps a fix is to change height to min-height?

**Comment by Sireks** [comment]
It is all about `optimizedCheckout-headingPrimary` classname. This css class was before the commit https://github.com/bigcommerce/checkout-js/commit/1f14515b74b282589419986a2a52673ec80e61f9.
The merchant can set merchants own custom styling for the checkout page throw `optimizedCheckout` .
I think the main reason why the step header has broken look is in Font that merchant chooses for styling.

**Comment by mattcoy-arcticleaf** [comment]
The point I'm trying to make is that increasing the font size should not break the step headers. Prior to this commit, increasing the font size did not break it. This site has had the same code on their checkout for months, with no issues until this commit. Something changed in this commit causing the step header to look broken. 

If you go to the Cornerstone demo site and increase the font-size of the headers to 65px, you can see the same issue:
<img width="717" alt="Screen Shot 2021-09-22 at 9 20 06 AM" src="https://user-images.githubusercontent.com/47044676/134382830-75680f69-4b1a-4b42-aec6-da8088ac92cb.png">

**Comment by Sireks** [comment]
I checked the issue and made those changed font-size for step headers and that what I got:
The main reason why it works as it is in styles of `.stepHeader-figure` class that didn't changed in the pr that you mentioned before.

I will tell the team about the issue.

Thanks for your time!

**Comment by Sireks** [comment]
@mattcoy-arcticleaf The fix was already deployed and it is available for stores on Tier 1 now. It may take couple days to deliver the fix to Tier 2 and Tier 3 stores (it is an automatic process).

**Comment by mattcoy-arcticleaf** [comment]
@serhii-tkachenko It does look better now, thanks!
