### ISSUE TITLE
Update Checkout Layout and JS behaviour

### ISSUE THREAD

**Issue by skydev2020** [bigcommerce/checkout-js#751]
### Expected behavior

![image](https://user-images.githubusercontent.com/57546027/141073340-13598cac-1e11-4281-980c-c88786655805.png)

I am trying to update this behavior in `CornerStone` templates.  I already created the issue but they told me to ask a question here.
https://github.com/bigcommerce/cornerstone/issues/2142
At the moment I can see the JS error in the console when there is no coupon available it.

### Actual behavior
It shows the JS error log.

### Steps to reproduce behavior
Add the items into cart and proceed to checkout page, and click 'Coupon/Gift Certificate' link.
![image](https://user-images.githubusercontent.com/57546027/141073886-331ca5d2-8dda-4e76-83c3-66197e14a8de.png)

I checked the `template/pages/checkout.html` but it has this code.
```
{{{ checkout.checkout_content }}}
```

How can I update the `{{{ checkout.checkout_content }}}`  and where is it?

**Comment by skydev2020** [comment]
any update on this?

**Comment by animesh1987** [comment]
Hey @skydev2020 is this still an issue? Also if I understand correctly the issue is the error console logs?
