### ISSUE TITLE
Local Development

### ISSUE THREAD

**Issue by pulpfree** [bigcommerce/checkout-js#753]
I’m attempting to create a "Custom Checkout" based on this repo. Could someone point me in the right direction regarding the setup of a local development environment?

I've found articles on how to install etc. [here](https://medium.com/bigcommerce-developer-blog/bigcommerce-checkout-is-now-open-source-39e823bc5b3b), but I find that process prohibitive as it's done on a live environment, and worse, the build file is cached restricting any iterative changes.

I imagine a sandbox environment with some mock data would work for just the checkout process, but curious how are other developers dealing with this?

Any help is appreciated.

Thanks,
Ron

**Comment by animesh1987** [comment]
Hi @pulpfree you can try disabling cache in network tab, that may help with build file not being cached. Also checkout right now as far as I know requires a live store to work on.

Apart from that we are aware regarding the developer experience not being the best. We will be looking at making the developer experience better in the next coming months. 

Please feel free to add more ideas/feedback to this comment thread so we can look at incorporating them.

Thanks.

**Comment by r742davis** [comment]
@pulpfree I just started working on the checkout as well and here's how I've set up the local dev environment.

I use a Sandbox Store I set up via BigCommerce, connect the Sandbox's Stencil CLI credentials to the store theme I want to work with, upload that theme to the Sandbox Store, and test the checkout on there. 

I run 3 things concurrently when developing locally:
1. `stencil start` local BC theme connected to custom checkout build on `http://localhost:3000`
2. `npm run dev` to launch the webpack watcher/builder
3. `npm run dev:server` to serve the build to the local address on your store (ex: `http://127.0.0.1:8080`)

Hope that helps! I'm still figuring it out myself

**Comment by pulpfree** [comment]
Thought I might provide some feedback here for anyone else struggling with this. See issue #754 for my comments on npm version problems. Apparently, npm v17.0.1 doesn't like the version of node-sass and I ended up using npm v14.17.5 successfully. I did make a bad assumption thinking my DevTools cache setting was checked :[ 

To avoid potential issues of caching on my production server, I'm bumping the version with `npm run release:version` before creating a build for production and using the `auto-loader-<VERSION>.js` file. Of course, that necessitates updating the `Script URL` path in the BG admin, but that beats serving stale files after letting your client know: "everything's been updated successfully".

I plan on distributing the production files on AWS S3 and Cloudfront. I would expect AWS to distribute (using Cloudfront) the files closest to the BG server location, anyone with thoughts/comments on this?

**Comment by skdhameliya** [comment]
1-which version is required of node and npm to setup checkout repo at local?
2-Do we need

**Comment by yaroslav-perec** [comment]
Hi! I'm still struggling with how to test this checkout, I've cloned the repo and did the following steps from the doc:

```
If you want to test your checkout implementation, you can run:

npm run dev:server
And enter the local URL for auto-loader-dev.js in Checkout Settings, e.g http://127.0.0.1:8080/auto-loader-dev.js
```

But when I'm navigating to the checkout page in my app I see the next (see attachment)

<img width="514" alt="Screenshot 2022-07-20 at 21 06 24" src="https://user-images.githubusercontent.com/30346881/180053112-8e55837e-8c77-45bd-a894-a0855d9da956.png">

Can anyone help with this? Maybe I missed something..

**Comment by Mubeen07** [comment]
I'm also facing the above issue
https://github.com/bigcommerce/checkout-js/issues/753#issuecomment-1190611609

**Comment by Mubeen07** [comment]
@bc-peng can you please address this issue as well?

**Comment by bc-peng** [comment]
> <img alt="Screenshot 2022-07-20 at 21 06 24" width="300" src="https://user-images.githubusercontent.com/30346881/180053112-8e55837e-8c77-45bd-a894-a0855d9da956.png">

This screenshot is a checkout page without a working `checkout-js`. 

`npm run dev:server` will serve files inside `/build` folder with the help from [http-server](https://www.npmjs.com/package/http-server). Maybe you can start with serving the main branch of https://github.com/bigcommerce/checkout-js.

Node and NPM requirements are stated at https://github.com/bigcommerce/checkout-js#requirements.

**Comment by Mubeen07** [comment]
@bc-peng I followed the documentation, I tried with ngrok instead of localhost but still facing this issue.
Unable to find any help till yet.

**Comment by bc-0dp** [comment]
Hello,

Have you checked your console for errors?
If a valid cart/checkout ID is not passed for instance. It will fail with errors in the console.

**Comment by Mubeen07** [comment]
@bc-0dp the only error I'm getting in console is
![image](https://user-images.githubusercontent.com/31301467/204459036-9bd271dd-f522-49b3-a354-b17fec1e7b64.png)

**Comment by matthewdolman** [comment]
I got th

> @bc-0dp the only error I'm getting in console is ![image](https://user-images.githubusercontent.com/31301467/204459036-9bd271dd-f522-49b3-a354-b17fec1e7b64.png)

I got this because I was running it in windows, if you are on a windows machine do the `npm dev` in wsl.

**Comment by bc-0dp** [comment]
We list in our requirements that a unix-like system is required. So very nice to have it verified that WLS is a feasible solution for windows users

**Comment by bc-0dp** [comment]
Hi @pulpfree 
Was this issue resolved for you in the end?

**Comment by pulpfree** [comment]
@bc-0dp we eventually abandoned this approach, so I can’t really comment.
