### ISSUE TITLE
MANIFEST_JSON is not defined

### ISSUE THREAD

**Issue by ken-gladeye** [bigcommerce/checkout-js#754]
Hi,

I've followed [this](https://github.com/bigcommerce/checkout-js#custom-checkout-installation) instruction here to try the custom checkout script on local but encounter this error when going to `/checkout` page

```
loader.ts?de6e:40 Uncaught (in promise) ReferenceError: MANIFEST_JSON is not defined
    at loadFiles (loader.ts?de6e:40)
    at eval (auto-loader.ts?5227:29)
    at step (tslib.es6.js?9ab4:100)
    at Object.eval [as next] (tslib.es6.js?9ab4:81)
    at eval (tslib.es6.js?9ab4:74)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js?9ab4:70)
    at autoLoad (auto-loader.ts?5227:21)
    at eval (auto-loader.ts?5227:21)
    at Module../src/app/auto-loader.ts (auto-loader-dev.js:8031)
```

Is there anything that I miss in the steps?

The script URL is `http://127.0.0.1:8081/auto-loader-dev.js`

**Comment by pulpfree** [comment]
Hey @ken-gladeye,
I experienced the same thing the other day and after a bit of frustration discovered that my node version was the problem.
During the `npm run dev `phase, you might, if you scroll up a bit see some warnings about node-sass not building. Oddly the build process doesn't halt on these errors and if you don't look carefully, it's easy to miss.

Check your node version with `node -v`. My system version is 17.0.1 and I'm using nvm to use 14.17.5, other versions might be fine as well.

Also, make sure that you've got caching turned off in your browser. I made the mistake of assuming my Chrome dev tools setting: `Disable cache (while DevTools is open)` was checked, (wasn't and began pulling at hair again), you can also check this in the Network panel.

**Comment by ken-gladeye** [comment]
@pulpfree thank you! and yes for me it's the combination of node version plus a TS error which I thought I can just ignore but it actually halts the whole webpack build process.
