### ISSUE TITLE
Why Unix based console is required.

### ISSUE THREAD

**Issue by rajguru827** [bigcommerce/checkout-js#767]
Can anyone pls explain, why we need Unix based console for building the app?

**Comment by dope-lab** [comment]
Well apparently, the core-js  needs to be excluded from the build(else your final build will throw `$ is not defined` error). For some reason, the webpack config written does not exclude that if your environment is windows. Anyway, I have figured out that if we change  the following code from webpack config, the build will work fine even with windows environment

Original code: (Line 174 - 177 & 301 - 304 )

```
exclude: [
      /\/node_modules\/core-js\//,
      /\/node_modules\/webpack\//,
    ],
```

Modified code:

```
exclude: [
        /\bcore-js\b/,
        /\bwebpack\b/,
      ],
```

**Comment by arosesiejdev** [comment]
@dope-lab I had made those following changes on the lines you mentioned, running on a Windows machine but still getting that $ is not defined error. What console steps are you doing to preview locally?

**Comment by rajguru827** [comment]
@arosesiejdev it worked for me in windows after updating the webpack config
