### ISSUE TITLE
Uncaught TypeError: $ is not a function es.array.join.js?a15b:14

### ISSUE THREAD

**Issue by anemos474** [bigcommerce/checkout-js#814]
Hi, i have some problem. 
I use instruction to install: https://github.com/bigcommerce/checkout-js, don`t change any, step by step
OS: Windows, use node: 14, npm: 6.

**Comment by dope-lab** [comment]
Just replace these codes in webpack config file

Original code: (Line 174 - 177 & 301 - 304 )

```
exclude: [
      /\/node_modules\/core-js\//,
      /\/node_modules\/webpack\//,
    ],
```

Modified code:

```
exclude: [
        /\bcore-js\b/,
        /\bwebpack\b/,
      ],
```
