### ISSUE TITLE
Update a Consignment - Method Not Allowed

### ISSUE THREAD

**Issue by inbaldoron** [bigcommerce/checkout-js#831]
I am testing my store and custom checkout locally.
When checking out I can't proceed past the Shipping step.
In network I see an error: 
405 Method Not Allowed
For PUT request:
`http://localhost:3000/api/storefront/checkouts/myCheckoutId/consignments/myConsignmentId?include=consignments.availableShippingOptions%2Ccart.lineItems.physicalItems.options%2Ccart.lineItems.digitalItems.options%2Ccustomer%2Cpromotions.banners%2C0`
From [API docs ](https://developer.bigcommerce.com/api-reference/b3A6MjMxMzYxOQ-update-a-consignment)I see this request should be valid.
Any help will be appreciated

**Comment by animesh1987** [comment]
Hey @inbaldoron this has already been reported as an issue with the stencil team https://github.com/bigcommerce/stencil-cli/issues/883. They should be look into it soon.

Please let us know if that fixes the issue for you once stencil issue is fixed so we can close this.

**Comment by inbaldoron** [comment]
accidentally closed, sorry
@[animesh1987](https://github.com/animesh1987)  I will follow up on the stencil issue. thank you very much for the quick reply

**Comment by animesh1987** [comment]
Hey @inbaldoron stencil issue seems to have been fixed, can you please test this and close the issue if it works as expected. Thanks

**Comment by bc-0dp** [comment]
Hi @inbaldoron I am closing this one due to inactivity. Do however feel free to open a new issue if the issue pesists. 🙇
