### ISSUE TITLE
Webpack not watching the file changes when running locally

### ISSUE THREAD

**Issue by Jugal-1Center** [bigcommerce/checkout-js#850]
The webpack is not watching and re-compiling the file changes after it has been initialized and hence requires us to hit the command `npm run dev` every time any changes are made. This makes local development time-consuming and frustrating as the initial command `npm run dev` takes about 10-15 mins to complete and get running, so doing this every time we make a small change is not ideal.

Is there anything we can do to fix this issue and is anyone else facing the same?
Any help would be highly appreciated.

**Comment by animesh1987** [comment]
Hey @Jugal-1Center we are working on a project to change the build process of the repo. Once that is done the developer experience should be much better.

**Comment by Jugal-1Center** [comment]
@animesh1987 Thanks for the update. Hope to see that change sooner as the current experience is pretty tedious.

**Comment by animesh1987** [comment]
@Jugal-1Center we have made some changes to build process and personally for me the build time has been reduced to around one minute for first build and way quicker for subsequent changes. Closing this for now.
