### ISSUE TITLE
Adding custom fields to checkout as order meta fields

### ISSUE THREAD

**Issue by lucashfreitas** [bigcommerce/checkout-js#868]
Hi There,

I want to add a dropdown/text field with extra options for extra options using the custom checkout, which later will be attached as meta fields in the order.

I am trying to customize the very minimum to make sure the checkout will keep the PCI compliance and also would be easier to update with newer versions from big commerce.

I forked this repository and currently implementing this new field and also customizing the UI/design of the checkout. Once it's done I am planning to check regularly for updates on this original repository to update my private fork. 

Does anyone have done something similar or have any advice to give?

Thanks

**Comment by animesh1987** [comment]
Hey @lucashfreitas sorry for the late reply for this. What you are asking is pretty much a project we want to look into next year which is checkout extensions. 

Adding the field might not be the issue, but updating the state that is maintained in SDK might be an issue (I am assuming you are using checkout SDK).

**Comment by lucashfreitas** [comment]
Hello animesh. Yeah, we ended up forking a version for the checkout (which is a quite painful process as we have to manually keep it in sync with the releases big commerce does which are quite frequent). 

o
