### ISSUE TITLE
"Taxes" is not customizable by lang files

### ISSUE THREAD

**Issue by pauliusinc** [bigcommerce/checkout-js#885]
The taxes_text field is not customizable by the lang.json files. 
My shop is written in German and I want to change the taxes field from "Tax" to "Davon Steuern". 

So I made it customizable in the code. I will create a PR for it.
On the other side the standard entry for subtotal_text is wrong. In german it is called "Zwischensumme".
The circumstance that there stands "Gesamtbetrag (netto)" breaks my whole shop logic, because brutto stands for "exclusive taxes" but my shop lists the prices incl. taxes because I set it so in the settings.

**Comment by bc-0dp** [comment]
Hi @funivan I will close this for now. If this issue persists, then don't hesitate to create a new issue. ❤️
