### ISSUE TITLE
Shipping section glitch on page refresh

### ISSUE THREAD

**Issue by rajguru827** [bigcommerce/checkout-js#890]
https://user-images.githubusercontent.com/17214716/171185393-08998ce9-5779-48e1-872d-8b3504f3ff9b.mp4

On refresh/navigating to the checkout page after adding the shipping address and selecting the shipping method, the shipping sections get expanded and after it's going to the payment section

**Comment by animesh1987** [comment]
Hey @rajguru827 this is a known issue and we will be look into it. Thanks.

**Comment by rajguru827** [comment]
@animesh1987 any updates on this issue? pls, let me know if I can help in solving this issue

**Comment by bc-0dp** [comment]
@bigcommerce/team-checkout
was this looked into?

**Comment by bc-0dp** [comment]
@rajguru827 just following up here, is the issue persisting?

**Comment by rajguru827** [comment]
@bc-0dp currently I am not working on Bigcommerce. So I am not sure still this issue exists or not.

**Comment by bc-0dp** [comment]
oh ok, thanks @rajguru827.
I'll close this one for now then.
Feel free to create a new issue if this is still a problem though.

❤️
