### ISSUE TITLE
Checkout is not leading with Uncaught (in promise) ReferenceError: MANIFEST_JSON is not defined

### ISSUE THREAD

**Issue by subinpauljoy** [bigcommerce/checkout-js#948]
Please help. After a build, the custom checkout page is blank with the following error. 

loader.ts:40 Uncaught (in promise) ReferenceError: MANIFEST_JSON is not defined
    at _ (loader.ts:40)
    at auto-loader.ts:29
    at tslib.es6.js:99
    at Object.next (tslib.es6.js:80)
    at tslib.es6.js:73
    at new Promise (<anonymous>)
    at i (tslib.es6.js:69)
    at auto-loader.ts:21
    at auto-loader.ts:21
    at auto-loader.ts:21

**Comment by bc-0dp** [comment]
Hi @subinpauljoy 
Did you manage to solve this in the end?

**Comment by bc-0dp** [comment]
@subinpauljoy I am closing this for now, please feel free to open a new issue if it persists.
❤️
