### ISSUE TITLE
Save New Address

### ISSUE THREAD

**Issue by aljunbellen17** [bigcommerce/checkout-js#992]
**New Address** being **save** in Address Book even though **shouldSaveAddress** is false either by unchecking the **tickbox** or altering **shouldSaveAddress** data to **false**

Video Reference: [Demo Link](https://loom.com/share/a203d9ab4f834e10a1d1b9bbe0b8c638)

<img width="695" alt="Screen Shot 2022-08-24 at 9 09 26 PM" src="https://user-images.githubusercontent.com/107860904/186426897-070f9caa-ac3b-472e-9aae-a9cb9f91f29a.png">

**Comment by animesh1987** [comment]
Hey @aljunbellen17 this is a known issue, we have the ticket in our backlog. We will try and get to it sometime soon. Sorry for the inconvenience.

**Comment by aljunbellen17** [comment]
Got it@animesh1987, please keep me posted here. Thank you very much!

**Comment by aljunbellen17** [comment]
Hi @animesh1987 any updates on this one? Thank you!

**Comment by bc-peng** [comment]
Hi @aljunbellen17. This bug will be fixed soon. We will deploy it next week.
https://github.com/bigcommerce/checkout-js/pull/1084

**Comment by animesh1987** [comment]
This has been deployed and fixed.
